server:
  version: "1.0.0"
  port: 8888
database:
  host: "localhost"
  port: 3306
  user: "root"
  name: "docman"
  password: "root"
logger:
  path: "logs/"
  max-age: 30
  max-size: 50
jwt:
  secret: outsider@outsider