server:
  version: "1.0.0"
  port: 8888
  api: /api/v1
database:
  host: localhost
  port: 5432
  name: "docman"
  user: "postgres"
  password: "123456"
logger:
  path: "logs/"
  max-age: "30"
  max-size: "50"
jwt:
  secret: "outsider@outsider"
casbin-rules:
  skip-urls:
    - "/login::POST"
    - "/registry::POST"
    - "/info::GET"
