server:
  version: "1.0.0"
  port: 8888
  api: /api/v1
database:
  host: localhost
  port: 3306
  name: "docman"
  user: "root"
  password: "root"
logger:
  path: "logs/"
  max-age: "30"
  max-size: "50"
jwt:
  secret: "outsider@outsider"
casbin-rules:
  skip-urls:
    - "/login::POST"
    - '/registry::POST'
    - '/info::GET'
